$axure.loadCurrentPage({
  "url":"tuanduien.html",
  "generationDate":new Date(1464936679724.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8ae09d33ab264f928043b143a415ebf9",
    "type":"Axure:Page",
    "name":"tuanduiEN",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF7FBFC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1832d8bace4a4fc3aa3b071a2b2321e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":80,
              "y":1176},
            "size":{
              "width":420,
              "height":284},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f819bbe2d0c43978918025840e4f24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":80,
                  "y":1176},
                "size":{
                  "width":420,
                  "height":284},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuanduien/u0.png"}},
{
          "id":"8ed3ca659b0d475fb031622ef2403c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":530,
              "y":893},
            "size":{
              "width":420,
              "height":250},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"172027704ab74c2ab1787cff59f8fd63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":530,
                  "y":893},
                "size":{
                  "width":420,
                  "height":250},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u2.png"}},
{
          "id":"0eacfd3b90a14cae987498e225faca25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":80,
              "y":890},
            "size":{
              "width":420,
              "height":250},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf12027bc4a04343915b1d2fe39ece17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":80,
                  "y":890},
                "size":{
                  "width":420,
                  "height":250},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u2.png"}},
{
          "id":"d421171a451f47ca9d4470248c495d6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":530,
              "y":600},
            "size":{
              "width":430,
              "height":250},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36c03c2c140f48ffa9d71d1ca8d9e6e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":530,
                  "y":600},
                "size":{
                  "width":430,
                  "height":250},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuanduien/u6.png"}},
{
          "id":"12f086fa2bc54f0cbec9a5ab0919ea52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFFFFFFF},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F},
{
                  "color":0xFFD6323F}]},
            "location":{
              "x":80,
              "y":600},
            "size":{
              "width":420,
              "height":250},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27313ce8de1f443d9751fe988ea51306",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFFFFFFF},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F},
{
                      "color":0xFFD6323F}]},
                "location":{
                  "x":80,
                  "y":600},
                "size":{
                  "width":420,
                  "height":250},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u2.png"}},
{
          "id":"19672da44e87406f8c4f0c150929ef99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1024,
              "height":213}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2219cdf541fc4955b92cec284e82a433",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1024,
                  "height":213}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u10.jpg"}},
{
          "id":"4dca57a35e1a490d91dad3f5db40f893",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":150},
            "size":{
              "width":242,
              "height":390},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d7acc6367f64661a485e490c0c0b90c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":150},
                "size":{
                  "width":242,
                  "height":390},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u21.png"}},
{
          "id":"89202d3a7a404aa1b52f445055fafdcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":150},
            "size":{
              "width":242,
              "height":390},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":3,
              "blurRadius":20,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68329ca141254756ad29cc15ec4fed30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":150},
                "size":{
                  "width":242,
                  "height":390},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":3,
                  "blurRadius":20,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u21.png"}},
{
          "id":"1d05f0e906414f9993182bd7d3fd5f85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":165},
            "size":{
              "width":110,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f919811abb4b4cb53bcf1b9b5080ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":165},
                "size":{
                  "width":110,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u25.png"}},
{
          "id":"9053b508d8934f93b17a0cb10ae2b1fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":614.5,
              "y":165},
            "size":{
              "width":112,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb800e5d9a241dc9f5d3800595bca3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":614.5,
                  "y":165},
                "size":{
                  "width":112,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u27.png"}},
{
          "id":"481f18474e084ba1a5e2bc0d016d8d92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":281,
              "y":281},
            "size":{
              "width":156,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"366ab11a746140b18dba4e90063be88e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":281,
                  "y":281},
                "size":{
                  "width":156,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f539a8f938da4cfc93334f7c5a463eea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":246,
              "y":310},
            "size":{
              "width":225,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e46e7f35ec48d2b599c3205fa46259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":246,
                  "y":310},
                "size":{
                  "width":225,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b0b1d47c40543debccc749ffcd262b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":252,
              "y":334},
            "size":{
              "width":219,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58e82c5f7d246a7a9c30509eebbc4ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":252,
                  "y":334},
                "size":{
                  "width":219,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c04187a50d79443f9bf596f29f3e4493",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":594,
              "y":280},
            "size":{
              "width":154,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef42bbb65184d34ad4779c4abe0b4cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":594,
                  "y":280},
                "size":{
                  "width":154,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43e8c7d790674ed39195c9383af77c4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":581,
              "y":307},
            "size":{
              "width":189,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd9254ad12f8430cac9b867cb3c1c9d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":581,
                  "y":307},
                "size":{
                  "width":189,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e248a8096844add98f84e5821885c39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":562,
              "y":322},
            "size":{
              "width":228,
              "height":208}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcaf639e39384ba3963d886e16c7dc58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":562,
                  "y":322},
                "size":{
                  "width":228,
                  "height":208}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e6661492e1c4823818a9d6e443ca6e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":629},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb6c5f198684e4cabfe4788306fe190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":629},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u41.png"}},
{
          "id":"be0d4fac1d9d4fc892c8cac0481c5a93",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":111.5,
              "y":760},
            "size":{
              "width":118,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6435e7ccb5d34c99bc2de17af8597125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":111.5,
                  "y":760},
                "size":{
                  "width":118,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b52495264cb641358e268a2ab07af9e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":90,
              "y":796},
            "size":{
              "width":182,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"421c3b0803674d42a07189c627077727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":796},
                "size":{
                  "width":182,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10914917722c4386a5dca0547cc93ac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":290,
              "y":620},
            "size":{
              "width":199,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757ebc47ee3044fbb74bd0766174fc87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":290,
                  "y":620},
                "size":{
                  "width":199,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97dd6afa125d4102bfe92cd84923e809",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":629},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49999ff1f171489c88fe433eac8a653a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":629},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u49.png"}},
{
          "id":"b4a6c73a52ba44998e7462708b3020ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":531,
              "y":760},
            "size":{
              "width":202,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c6234a33974dc29d99ca8b38569978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":531,
                  "y":760},
                "size":{
                  "width":202,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16daf8ddacba4ba7b31f65a5824721bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":549,
              "y":796},
            "size":{
              "width":171,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cb97395d53649f1ab4e9ca37eda9d1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":549,
                  "y":796},
                "size":{
                  "width":171,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5df480cae80425f9c751064c1b44e21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":740,
              "y":608},
            "size":{
              "width":216,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9ec96750824941af56a5481c46b0a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":740,
                  "y":608},
                "size":{
                  "width":216,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a60e88cd41d471ca97291cd84638b20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":918},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"437715e8cab04ca899f5ff6e4cb568d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":918},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u57.png"}},
{
          "id":"765bb8e7c85844edb2f79a8292861564",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":583,
              "y":1059},
            "size":{
              "width":101,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e06b4259d6a4464bad057aee6cabdd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":583,
                  "y":1059},
                "size":{
                  "width":101,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6d6fda4d5c743059216ceaff342ecd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":542,
              "y":1097},
            "size":{
              "width":179,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88c9218726a8442889daa09a73561e6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":542,
                  "y":1097},
                "size":{
                  "width":179,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e8f4200e9164f6db2a6ca5c643a8719",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":741,
              "y":910},
            "size":{
              "width":197,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6789012f5c594f9e817878eb6b9c715c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":741,
                  "y":910},
                "size":{
                  "width":197,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d82b3ab2fd9e40cfab3f64d8416d64ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":918},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ae1d1923f0c4dbe9a54b268ad17820e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":918},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u65.png"}},
{
          "id":"a3729275ae044937b3f151c6e851e087",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":94,
              "y":1059},
            "size":{
              "width":155,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9b69b7dccd24a1786fe715b7e93d3da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":94,
                  "y":1059},
                "size":{
                  "width":155,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc714abfaa5f4932ae9b30382f1006e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":112,
              "y":1091},
            "size":{
              "width":118,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f8a9cb1b1ef49368f3ccd936728d224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":112,
                  "y":1091},
                "size":{
                  "width":118,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5dfc8aec2fb4e189545ada82e87fd25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":290,
              "y":910},
            "size":{
              "width":192,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"472ce1366c604c12a7e34fabd7af92c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":290,
                  "y":910},
                "size":{
                  "width":192,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cca81a5ee53549a5b2f36d8f12966bf3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":1215},
            "size":{
              "width":117,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e74919b441db480eac4667e2606c533d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":1215},
                "size":{
                  "width":117,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u73.png"}},
{
          "id":"024c5544bb8a4741b41753d2ab993057",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "verticalAlignment":"bottom",
            "location":{
              "x":133.5,
              "y":1353},
            "size":{
              "width":94,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32f718e85c44498ca4751f4e1a2fd0b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "verticalAlignment":"bottom",
                "location":{
                  "x":133.5,
                  "y":1353},
                "size":{
                  "width":94,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f7ae7b3c8b145a994271daaa779f507",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":114,
              "y":1389},
            "size":{
              "width":136,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0fa983566014490999877b24a8bbbcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":114,
                  "y":1389},
                "size":{
                  "width":136,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e9545f1963f45eca44567557ba9dca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "lineSpacing":"16px",
            "location":{
              "x":290,
              "y":1183},
            "size":{
              "width":210,
              "height":195}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e30a14b698b4a37af792bbc9ec21a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "lineSpacing":"16px",
                "location":{
                  "x":290,
                  "y":1183},
                "size":{
                  "width":210,
                  "height":195}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51e3805d1b9d4452be04be286442a25e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF373737},
            "location":{
              "x":0,
              "y":1500},
            "size":{
              "width":1024,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46881abdd7c1416eaff20921990188de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF373737},
                "location":{
                  "x":0,
                  "y":1500},
                "size":{
                  "width":1024,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u72.png"}},
{
          "id":"0c7bc6d7722c4c4c991f37283ca07b42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":0,
              "y":1600},
            "size":{
              "width":1024,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63df6fb1831146d2a7c76c6981e89a8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":0,
                  "y":1600},
                "size":{
                  "width":1024,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u76.png"}},
{
          "id":"ea73abcb7edc402da1a2c36f7750414b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":295,
              "y":530},
            "size":{
              "width":128,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf9b46afdbb4334b8f123948a3da2c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":295,
                  "y":530},
                "size":{
                  "width":128,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u85.png"}},
{
          "id":"1ac93d7ed3804714806c5edab9b67cd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":606,
              "y":530},
            "size":{
              "width":128,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed3765ca988b4e549f8f9dcc826f8666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":606,
                  "y":530},
                "size":{
                  "width":128,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tuandui/u85.png"}},
{
          "id":"21b3401af90340eeaf86fc341d47ac76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":313,
              "y":1542},
            "size":{
              "width":398,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"490f6e7bbd85404eb453ec591dcba0b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":313,
                  "y":1542},
                "size":{
                  "width":398,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e67fe9dbc5de492eaa975596cf3167e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":857,
              "y":21},
            "size":{
              "width":58,
              "height":22},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f78da43b25c4cb39b2fba3ae3d74e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":857,
                  "y":21},
                "size":{
                  "width":58,
                  "height":22},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u78.png"}},
{
          "id":"cc27cc2c55f242b69e9165968855d038",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD6323F},
            "location":{
              "x":891,
              "y":22},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29262b1fdae4448f88c0701b13ae936e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD6323F},
                "location":{
                  "x":891,
                  "y":22},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u80.png"}},
{
          "id":"1e3c48bfae0a4b3884f08ec5ed98f573",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD6323F,
              "opacity":1},
            "location":{
              "x":864,
              "y":24},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718d43a086bc4c39b1bf5e31230e80e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD6323F,
                  "opacity":1},
                "location":{
                  "x":864,
                  "y":24},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 tuandui",
                      "target":{
                        "targetType":"page",
                        "url":"tuandui.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fe1693c05034e979baf98a446ee2af0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":892,
              "y":24},
            "size":{
              "width":19,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380fdf54618d42fe8c9b5e1657ec5d3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":892,
                  "y":24},
                "size":{
                  "width":19,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 tuanduiEN",
                      "target":{
                        "targetType":"page",
                        "url":"tuanduien.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"523e8ae3be604c9c8fbb84f7483eb8d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":476,
              "y":24},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"198b1876890743078d66320d7e843363",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":476,
                  "y":24},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 indexEN",
                      "target":{
                        "targetType":"page",
                        "url":"indexen.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["a745c1bdeeb044ab941570084747ccf0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["5bea011e5e88490fa25c5247b46fef6a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["5bea011e5e88490fa25c5247b46fef6a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["a745c1bdeeb044ab941570084747ccf0"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"cad1b2ed9bb74ace923876250d62d81f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":540,
              "y":24},
            "size":{
              "width":112,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5bb2c04c6244f44813978af08fe125b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":540,
                  "y":24},
                "size":{
                  "width":112,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 fuwuEN",
                      "target":{
                        "targetType":"page",
                        "url":"fuwuen.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["913b31efceff4091981d8be8803d8a80"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["5bea011e5e88490fa25c5247b46fef6a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["913b31efceff4091981d8be8803d8a80"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["5bea011e5e88490fa25c5247b46fef6a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f621ec129390458ab9973048c4656faa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":650,
              "y":24},
            "size":{
              "width":123,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f77d55df9140f19d593acb9d4dfc09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":650,
                  "y":24},
                "size":{
                  "width":123,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 tuanduiEN",
                      "target":{
                        "targetType":"page",
                        "url":"tuanduien.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"2d74e52232b543cb86deedfa8015d01b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "location":{
              "x":773,
              "y":24},
            "size":{
              "width":78,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4607de166864ee2bf2ede0d00292684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "location":{
                  "x":773,
                  "y":24},
                "size":{
                  "width":78,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 cont,<br>email",
                      "objectsToFades":[{
                          "objectPath":["6a99d928e2434e1b93ce8a033bcec88b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b72f40d00e6d4b90aeed0f28b8304acb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 4",
                      "objectsToFades":[{
                          "objectPath":["532c61a3873846e4a32be0d72ad04c2c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 3",
                      "objectsToFades":[{
                          "objectPath":["5bea011e5e88490fa25c5247b46fef6a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3",
                      "objectsToFades":[{
                          "objectPath":["5bea011e5e88490fa25c5247b46fef6a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 4",
                      "objectsToFades":[{
                          "objectPath":["532c61a3873846e4a32be0d72ad04c2c"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a745c1bdeeb044ab941570084747ccf0",
          "label":"1",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":489,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u94_line.png"}},
{
          "id":"913b31efceff4091981d8be8803d8a80",
          "label":"2",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":583.5,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u94_line.png"}},
{
          "id":"5bea011e5e88490fa25c5247b46fef6a",
          "label":"3",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":696,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u94_line.png"}},
{
          "id":"532c61a3873846e4a32be0d72ad04c2c",
          "label":"4",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":false,
          "style":{
            "location":{
              "x":794,
              "y":46},
            "size":{
              "width":25,
              "height":10},
            "visible":false,
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/1_u94_line.png"}},
{
          "id":"6a99d928e2434e1b93ce8a033bcec88b",
          "label":"cont",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "verticalAlignment":"bottom",
            "fill":{
              "fillType":"solid",
              "color":0xFFF13C5B},
            "location":{
              "x":752,
              "y":38},
            "size":{
              "width":235,
              "height":28},
            "visible":false,
            "rotation":"180",
            "textRotation":"180",
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e329a1842349478c8dbaad48ec44a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "verticalAlignment":"bottom",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF13C5B},
                "location":{
                  "x":752,
                  "y":38},
                "size":{
                  "width":235,
                  "height":28},
                "visible":false,
                "rotation":"180",
                "textRotation":"180",
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/cont_u106.png"}},
{
          "id":"b72f40d00e6d4b90aeed0f28b8304acb",
          "label":"email",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":733,
              "y":46},
            "size":{
              "width":270,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfaba84a897e45adad524cf415bf69d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":733,
                  "y":46},
                "size":{
                  "width":270,
                  "height":30},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 email,<br>cont",
                      "objectsToFades":[{
                          "objectPath":["b72f40d00e6d4b90aeed0f28b8304acb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["6a99d928e2434e1b93ce8a033bcec88b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1832d8bace4a4fc3aa3b071a2b2321e0":{
      "scriptId":"u0"},
    "2f819bbe2d0c43978918025840e4f24e":{
      "scriptId":"u1"},
    "8ed3ca659b0d475fb031622ef2403c17":{
      "scriptId":"u2"},
    "172027704ab74c2ab1787cff59f8fd63":{
      "scriptId":"u3"},
    "0eacfd3b90a14cae987498e225faca25":{
      "scriptId":"u4"},
    "cf12027bc4a04343915b1d2fe39ece17":{
      "scriptId":"u5"},
    "d421171a451f47ca9d4470248c495d6a":{
      "scriptId":"u6"},
    "36c03c2c140f48ffa9d71d1ca8d9e6e5":{
      "scriptId":"u7"},
    "12f086fa2bc54f0cbec9a5ab0919ea52":{
      "scriptId":"u8"},
    "27313ce8de1f443d9751fe988ea51306":{
      "scriptId":"u9"},
    "19672da44e87406f8c4f0c150929ef99":{
      "scriptId":"u10"},
    "2219cdf541fc4955b92cec284e82a433":{
      "scriptId":"u11"},
    "4dca57a35e1a490d91dad3f5db40f893":{
      "scriptId":"u12"},
    "1d7acc6367f64661a485e490c0c0b90c":{
      "scriptId":"u13"},
    "89202d3a7a404aa1b52f445055fafdcc":{
      "scriptId":"u14"},
    "68329ca141254756ad29cc15ec4fed30":{
      "scriptId":"u15"},
    "1d05f0e906414f9993182bd7d3fd5f85":{
      "scriptId":"u16"},
    "15f919811abb4b4cb53bcf1b9b5080ca":{
      "scriptId":"u17"},
    "9053b508d8934f93b17a0cb10ae2b1fa":{
      "scriptId":"u18"},
    "feb800e5d9a241dc9f5d3800595bca3a":{
      "scriptId":"u19"},
    "481f18474e084ba1a5e2bc0d016d8d92":{
      "scriptId":"u20"},
    "366ab11a746140b18dba4e90063be88e":{
      "scriptId":"u21"},
    "f539a8f938da4cfc93334f7c5a463eea":{
      "scriptId":"u22"},
    "31e46e7f35ec48d2b599c3205fa46259":{
      "scriptId":"u23"},
    "6b0b1d47c40543debccc749ffcd262b9":{
      "scriptId":"u24"},
    "d58e82c5f7d246a7a9c30509eebbc4ff":{
      "scriptId":"u25"},
    "c04187a50d79443f9bf596f29f3e4493":{
      "scriptId":"u26"},
    "8ef42bbb65184d34ad4779c4abe0b4cb":{
      "scriptId":"u27"},
    "43e8c7d790674ed39195c9383af77c4e":{
      "scriptId":"u28"},
    "fd9254ad12f8430cac9b867cb3c1c9d5":{
      "scriptId":"u29"},
    "4e248a8096844add98f84e5821885c39":{
      "scriptId":"u30"},
    "bcaf639e39384ba3963d886e16c7dc58":{
      "scriptId":"u31"},
    "9e6661492e1c4823818a9d6e443ca6e5":{
      "scriptId":"u32"},
    "4fb6c5f198684e4cabfe4788306fe190":{
      "scriptId":"u33"},
    "be0d4fac1d9d4fc892c8cac0481c5a93":{
      "scriptId":"u34"},
    "6435e7ccb5d34c99bc2de17af8597125":{
      "scriptId":"u35"},
    "b52495264cb641358e268a2ab07af9e3":{
      "scriptId":"u36"},
    "421c3b0803674d42a07189c627077727":{
      "scriptId":"u37"},
    "10914917722c4386a5dca0547cc93ac7":{
      "scriptId":"u38"},
    "757ebc47ee3044fbb74bd0766174fc87":{
      "scriptId":"u39"},
    "97dd6afa125d4102bfe92cd84923e809":{
      "scriptId":"u40"},
    "49999ff1f171489c88fe433eac8a653a":{
      "scriptId":"u41"},
    "b4a6c73a52ba44998e7462708b3020ed":{
      "scriptId":"u42"},
    "32c6234a33974dc29d99ca8b38569978":{
      "scriptId":"u43"},
    "16daf8ddacba4ba7b31f65a5824721bf":{
      "scriptId":"u44"},
    "8cb97395d53649f1ab4e9ca37eda9d1c":{
      "scriptId":"u45"},
    "c5df480cae80425f9c751064c1b44e21":{
      "scriptId":"u46"},
    "8e9ec96750824941af56a5481c46b0a8":{
      "scriptId":"u47"},
    "0a60e88cd41d471ca97291cd84638b20":{
      "scriptId":"u48"},
    "437715e8cab04ca899f5ff6e4cb568d9":{
      "scriptId":"u49"},
    "765bb8e7c85844edb2f79a8292861564":{
      "scriptId":"u50"},
    "2e06b4259d6a4464bad057aee6cabdd3":{
      "scriptId":"u51"},
    "f6d6fda4d5c743059216ceaff342ecd1":{
      "scriptId":"u52"},
    "88c9218726a8442889daa09a73561e6a":{
      "scriptId":"u53"},
    "6e8f4200e9164f6db2a6ca5c643a8719":{
      "scriptId":"u54"},
    "6789012f5c594f9e817878eb6b9c715c":{
      "scriptId":"u55"},
    "d82b3ab2fd9e40cfab3f64d8416d64ab":{
      "scriptId":"u56"},
    "6ae1d1923f0c4dbe9a54b268ad17820e":{
      "scriptId":"u57"},
    "a3729275ae044937b3f151c6e851e087":{
      "scriptId":"u58"},
    "c9b69b7dccd24a1786fe715b7e93d3da":{
      "scriptId":"u59"},
    "fc714abfaa5f4932ae9b30382f1006e4":{
      "scriptId":"u60"},
    "1f8a9cb1b1ef49368f3ccd936728d224":{
      "scriptId":"u61"},
    "a5dfc8aec2fb4e189545ada82e87fd25":{
      "scriptId":"u62"},
    "472ce1366c604c12a7e34fabd7af92c7":{
      "scriptId":"u63"},
    "cca81a5ee53549a5b2f36d8f12966bf3":{
      "scriptId":"u64"},
    "e74919b441db480eac4667e2606c533d":{
      "scriptId":"u65"},
    "024c5544bb8a4741b41753d2ab993057":{
      "scriptId":"u66"},
    "32f718e85c44498ca4751f4e1a2fd0b1":{
      "scriptId":"u67"},
    "9f7ae7b3c8b145a994271daaa779f507":{
      "scriptId":"u68"},
    "d0fa983566014490999877b24a8bbbcc":{
      "scriptId":"u69"},
    "0e9545f1963f45eca44567557ba9dca4":{
      "scriptId":"u70"},
    "7e30a14b698b4a37af792bbc9ec21a4f":{
      "scriptId":"u71"},
    "51e3805d1b9d4452be04be286442a25e":{
      "scriptId":"u72"},
    "46881abdd7c1416eaff20921990188de":{
      "scriptId":"u73"},
    "0c7bc6d7722c4c4c991f37283ca07b42":{
      "scriptId":"u74"},
    "63df6fb1831146d2a7c76c6981e89a8b":{
      "scriptId":"u75"},
    "ea73abcb7edc402da1a2c36f7750414b":{
      "scriptId":"u76"},
    "fbf9b46afdbb4334b8f123948a3da2c4":{
      "scriptId":"u77"},
    "1ac93d7ed3804714806c5edab9b67cd1":{
      "scriptId":"u78"},
    "ed3765ca988b4e549f8f9dcc826f8666":{
      "scriptId":"u79"},
    "21b3401af90340eeaf86fc341d47ac76":{
      "scriptId":"u80"},
    "490f6e7bbd85404eb453ec591dcba0b2":{
      "scriptId":"u81"},
    "e67fe9dbc5de492eaa975596cf3167e8":{
      "scriptId":"u82"},
    "8f78da43b25c4cb39b2fba3ae3d74e28":{
      "scriptId":"u83"},
    "cc27cc2c55f242b69e9165968855d038":{
      "scriptId":"u84"},
    "29262b1fdae4448f88c0701b13ae936e":{
      "scriptId":"u85"},
    "1e3c48bfae0a4b3884f08ec5ed98f573":{
      "scriptId":"u86"},
    "718d43a086bc4c39b1bf5e31230e80e8":{
      "scriptId":"u87"},
    "8fe1693c05034e979baf98a446ee2af0":{
      "scriptId":"u88"},
    "380fdf54618d42fe8c9b5e1657ec5d3c":{
      "scriptId":"u89"},
    "523e8ae3be604c9c8fbb84f7483eb8d1":{
      "scriptId":"u90"},
    "198b1876890743078d66320d7e843363":{
      "scriptId":"u91"},
    "cad1b2ed9bb74ace923876250d62d81f":{
      "scriptId":"u92"},
    "b5bb2c04c6244f44813978af08fe125b":{
      "scriptId":"u93"},
    "f621ec129390458ab9973048c4656faa":{
      "scriptId":"u94"},
    "c9f77d55df9140f19d593acb9d4dfc09":{
      "scriptId":"u95"},
    "2d74e52232b543cb86deedfa8015d01b":{
      "scriptId":"u96"},
    "f4607de166864ee2bf2ede0d00292684":{
      "scriptId":"u97"},
    "a745c1bdeeb044ab941570084747ccf0":{
      "scriptId":"u98"},
    "913b31efceff4091981d8be8803d8a80":{
      "scriptId":"u99"},
    "5bea011e5e88490fa25c5247b46fef6a":{
      "scriptId":"u100"},
    "532c61a3873846e4a32be0d72ad04c2c":{
      "scriptId":"u101"},
    "6a99d928e2434e1b93ce8a033bcec88b":{
      "scriptId":"u102"},
    "58e329a1842349478c8dbaad48ec44a3":{
      "scriptId":"u103"},
    "b72f40d00e6d4b90aeed0f28b8304acb":{
      "scriptId":"u104"},
    "bfaba84a897e45adad524cf415bf69d1":{
      "scriptId":"u105"}}});